# Generated by Django 2.2.2 on 2020-12-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('energy', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbo', models.FloatField()),
            ],
        ),
    ]
