# Generated by Django 2.2.2 on 2020-12-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='energy',
            field=models.FloatField(),
        ),
    ]
